### ISSUE TITLE
Creating standard JSON string output w/ formatting requires quite some code

### ISSUE THREAD

**Issue by kiesel** [xp-forge/json#3]
In order to produce human-readable JSON output, I have to write this code:

``` php
use text\json\StringOutput;
use text\json\WrappedFormat;
use text\json\Format;

// [...]

$json = new StringOutput(new WrappedFormat('  ', ~Format::ESCAPE_SLASHES));
$json->write([
  // ... data ...
]);
$readable= $json->bytes();
```

**Comment by thekid** [comment]
Yes, this could be simpler :+1: 
- [x] Make creating JSON strings simpler
- [x] Make creating format instances simpler

**Comment by thekid** [comment]
## Make creating JSON strings simpler, Idea 1

Create a static method

``` php
// string of(var $data[, text.json.Format $format])
$readable= StringOutput::of($data);
```

**Comment by thekid** [comment]
## Make creating JSON strings simpler, Idea 2

Create a `Json` class

``` php
// string of(var $data[, text.json.Format $format])
$readable= Json::of($data);

// var read(text.json.Input $in)
$data= Json::read($input);

// text.json.Output write(var $data, text.json.Output $out)
$readable= Json::write($data, new StringOutput())->bytes();
```

**Comment by thekid** [comment]
## Make creating JSON strings simpler, Idea 3

(Placeholder)

**Comment by thekid** [comment]
## Make creating format instances simpler, idea 1

Simply make indent level "changeable" (in reality, returns a clone with the changed indentation level).

``` php
// Same as new WrappedFormat('  ', ~Format::ESCAPE_SLASHES);
$format= Format::$NATURAL->indenting('  ');
```

**Comment by thekid** [comment]
## Make creating format instances simpler, idea 2

Create dense() and wrapped() methods as factories for `DenseFormat` and `WrappedFormat`, giving the latter a parameter to supply indenting level:

``` php
$format= Format::dense();
$format= Format::wrapped('  ');   // Escaping slashes off by default

// Alternatively, using the Json class from above
$format= Json::dense();
$format= Json::wrapped('  ');
```

**Comment by thekid** [comment]
## Make creating format instances simpler, idea 3

(Placeholder)

**Comment by thekid** [comment]
# Putting it together

My favorites are no. 2 and no. 2. Rewriting your example from above, we would have:

``` php
use text\json\Json;
use text\json\Format;

$readable= Json::of($data, Format::wrapped('  '));
```

@kiesel See #4 - what do you think? What are your ideas?

**Comment by thekid** [comment]
## Further reading
- https://docs.python.org/3/library/json.html
- http://ruby-doc.org/stdlib-2.0.0/libdoc/json/rdoc/JSON.html
- I haven't found a short and concise API in Java, Groovy or Scala

**Comment by thekid** [comment]
PR #4 has been merged. If this doesn't solve the issue for you, please reopen.
